# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Thatcher Larson
title: Computer Science Student
email: larsonthatch@gmail.com
website: https://thatcherlarson.github.io/

# Social links
# twitter_username: facespics
github_username:  ThatcherLarson
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: thatcherlarson
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a passionate Software Developer currently located in the Winona-La Crosse area.  

  

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
